### ISSUE TITLE
Setting up React Native app

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#76]
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/58
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/59
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/60
