### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#77]
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/55
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/56
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/57
