### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#78]
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/61
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/62
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/63
