### ISSUE TITLE
Layout and routes

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#79]
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/64
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/65
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/66
- [x] Implement protected routes
