### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#80]
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/67
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/68
- [ ] https://github.com/RitehWebTeam/infobip-rimatch/issues/69
