### ISSUE TITLE
Settings menu

### ISSUE THREAD

**Issue by SaraKalcic** [RitehWebTeam/infobip-rimatch#81]
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/70
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/71
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/72
- [x] https://github.com/RitehWebTeam/infobip-rimatch/issues/73
